function generateName(){
    var adj = ["attractive","bald","beautiful","chubby","clean","dazzling","drab","elegant","fancy","fit","flabby","glamorous","gorgeous","handsome","long","magnificent","muscular","plain","plump","quaint","scruffy","shapely","short","skinny","stocky","ugly","unkempt","unsightly","ashy","black","blue","gray","green","icy","lemon","mango","orange","purple","red","salmon","white","yellow","alive","better","careful","clever","dead","easy","famous","gifted","hallowed","helpful","important","inexpensive","mealy","mushy","odd","poor","powerful","rich","shy","tender","unimportant","uninterested","vast","wrong","aggressive","agreeable","ambitious","brave","calm","delightful","eager","faithful","gentle","happy","jolly","kind","lively","nice","obedient","polite","proud","silly","thankful","victorious","witty","wonderful","zealous","angry","bewildered","clumsy","defeated","embarrassed","fierce","grumpy","helpless","itchy","jealous","lazy","mysterious","nervous","obnoxious","panicky","pitiful","repulsive","scary","thoughtless","uptight","worried","broad","chubby","crooked","curved","deep","flat","high","hollow","low","narrow","refined","round","shallow","skinny","square","steep","straight","wide","big","colossal","fat","gigantic","great","huge","immense","large","little","mammoth","massive","microscopic","miniature","petite","puny","scrawny","short","small","tall","teeny","tiny","crashing","deafening","echoing","faint","harsh","hissing","howling","loud","melodic","noisy","purring","quiet","rapping","raspy","rhythmic","screeching","shrilling","squeaking","thundering","tinkling","wailing","whining","whispering","ancient","brief","early","fast","future","late","long","modern","old","old-fashioned","prehistoric","quick","rapid","short","slow","swift","young","acidic","bitter","cool","creamy","delicious","disgusting","fresh","greasy","juicy","hot","moldy","nutritious","nutty","putrid","rancid","ripe","rotten","salty","savory","sour","spicy","spoiled","stale","sweet","tangy","tart","tasteless","tasty","yummy","breezy","bumpy","chilly","cold","cool","cuddly","damaged","damp","dirty","dry","flaky","fluffy","freezing","greasy","hot","icy","loose","melted","prickly","rough","shaggy","sharp","slimy","sticky","strong","tight","uneven","warm","weak","wet","wooden","abundant","billions","enough","few","full","hundreds","incalculable","limited","little","many","most","millions","numerous","scarce","some","sparse","substantial","thousands"]
    var ani_name = ["alligator","ant","bear","bee","bird","camel","cat","cheetah","chicken","chimpanzee","cow","crocodile","deer","dog","dolphin","duck","eagle","elephant","fish","fly","fox","frog","giraffe","goat","goldfish","hamster","hippopotamus","horse","kangaroo","kitten","lion","lobster","monkey","octopus","owl","panda","pig","puppy","rabbit","rat","scorpion","seal","shark","sheep","snail","snake","spider","squirrel","tiger","turtle","wolf","zebra"]

    var ran_num_1 = parseInt(Math.random() * adj.length);
    var ran_num_2 = parseInt(Math.random() * ani_name.length);

    name = adj[ran_num_1]+ " "+ ani_name[ran_num_2];
    
    document.getElementById("gen_text").innerHTML = name;
}

document.onload = generateName();
document.getElementById("button").addEventListener("click", generateName);